---
- name: "Playing with Ansible"
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  hosts: localhost
  connection: local
  tasks:
    - name: Configure Emacs
      copy:
        src: conf/emacs
        dest: '{{ local_home }}/.emacs'
        mode: u=rw,g=rw,o=r
    - name: Configure Git
      template:
        src: conf/gitconfig.j2
        dest: '{{ local_home }}/.gitconfig'
        mode: u=rw,g=rw,o=r
    - name: Configure Vim
      template:
        src: conf/vimrc
        dest: '{{ local_home }}/.vimrc'
        mode: u=rw,g=rw,o=r
