---
- import_playbook: vim.yml
- name: "Setup configuration files"
  hosts: localhost
  connection: local
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install miscellaneous
      package:
        name:
          - git
          - i3
          - arandr
          - autorandr
          - zsh
          - konsole
          - tree
        state: present
      become: true
    - name: Check if Autorandr is already configured
      stat:
        path: '{{ local_home }}/.config/autorandr'
      register: autorandr_configuration
    - name: Configure autorandr
      copy:
        src: conf/autorandr
        dest: '{{ local_home }}/.config/'
        mode: u=rw,g=rw,o=r
    - name: Activate autorandr configuration
      command: autorandr --change
      # allow autrandr to fail when no display is found
      ignore_errors: true
      when: not autorandr_configuration.stat.exists
    - name: Configure Git
      template:
        src: conf/gitconfig.j2
        dest: '{{ local_home }}/.gitconfig'
        mode: u=rw,g=rw,o=r
    - name: Ensure that config directory exist
      file:
        path: "{{ local_home }}/.config"
        state: directory
        recurse: false
        mode: 0775
    - name: Ensure that I3 directory exist
      file:
        path: "{{ local_home }}/.config/i3"
        state: directory
        recurse: false
        mode: 0775
    - name: Configure I3
      template:
        src: conf/i3-config
        dest: '{{ local_home }}/.config/i3/config'
        mode: u=rw,g=rw,o=r
    - name: Ensure that dot-local directory exist
      file:
        path: "{{ local_home }}/.local"
        state: directory
        recurse: false
        mode: 0775
    - name: Ensure that share directory exist
      file:
        path: "{{ local_home }}/.local/share"
        state: directory
        recurse: false
        mode: 0775
    - name: Configure Konsole
      template:
        src: conf/konsole.profile
        dest: '{{ local_home }}/.local/share/konsole/best.profile'
        mode: u=rw,g=rw,o=r
    - name: Change user shell to zsh
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
    - name: Check if Zsh is already configured
      stat:
        path: '{{ local_home }}/.oh-my-zsh'
      register: oh_my_zsh_configuration
    - name: Install Oh My Zsh
      # Urls should be fine
      # yamllint disable-line rule:line-length
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not oh_my_zsh_configuration.stat.exists
