---
- import_playbook: vim.yml
- name: "Setup configuration files"
  hosts: localhost
  connection: local
  tasks:
    - name: Install miscellaneous
      package:
        name:
          - git
        state: present
      become: true
    - name: Configure Git
      template:
        src: conf/gitconfig.j2
        dest: '{{ local_home }}/.gitconfig'
        mode: u=rw,g=rw,o=r
